@Library('sym-pipeline') _

node("build-directory-jenkins-agent") {

    String project = 'directory-scimple'
    String projectOrg = 'SymphonyOSF'
    withEnv([
            "GIT_REPO=${project}",
            "GIT_ORG=${projectOrg}",
            "GIT_BRANCH=${env.BRANCH_NAME}",
    ]) {

        stage('Build and test jar') {
            gitCheckout()
            mvn('clean package -Dpmd.skip=true -Dspotbugs.skip=true')
        }

        stage("Publish the packages") {
            def readPom = readMavenPom file: 'pom.xml'
            def version = "${readPom.version}"
            def artifactsToDeploy = [ // path, name
              ['scim-spec/scim-spec-schema', 'scim-spec-schema'],
              ['scim-server', 'scim-server'],
              ['scim-core', 'scim-core']
            ]
            artifactsToDeploy.each { artifact ->
                def path = artifact[0]
                def name = artifact[1]
              deployOnArtifactory("${path}/target/${name}-${version}.jar", 'cip-local-dev/directory-scimple/')
            }
        }
    }
}

def mvn(String cmd) {
    withCredentials([file(credentialsId: 'maven-settings', variable: 'settings_xml')]) {
        sh 'mkdir -p /home/jenkins/.m2'
        sh 'base64 -d \$settings_xml > /home/jenkins/.m2/settings.xml'
        sh "mvn -B ${cmd}"
    }
}

def deployOnArtifactory(filename, target_folder) {
    echo "Deploying the ${filename} -> ${target_folder} to Artifactory"
    def artifactoryServer = Artifactory.server 'Symphony-Production-Artifactory'
    def buildInfo = Artifactory.newBuildInfo()
    buildInfo.name = "${filename}"
    def uploadSpec = """{
        "files": [{
            "pattern": "${filename}",
            "target": "${target_folder}"
            }
            ]
    }"""
    artifactoryServer.upload(uploadSpec, true)
    artifactoryServer.publishBuildInfo(buildInfo)
}
