#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Build Reproducibility Check

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout
        default: 'develop'
        type: string

env:
  MAVEN_ARGS: -V -B --no-transfer-progress

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Java ${{ matrix.java }}-zulu
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 #v4.7.0
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
          cache: '' # disabled

      - name: Running Maven
        run: |
          ./mvnw install  \
            -Ddevelocity.cache.local.enabled=false \
            -Ddevelocity.cache.remote.enabled=false
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DIRECTORY_DEVELOCITY_ACCESS_KEY }}

      - name: Running Maven again to check reproducibility
        run: |
          ./mvnw clean verify artifact:compare  \
            -Ddevelocity.cache.local.enabled=false \
            -Ddevelocity.cache.remote.enabled=false
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DIRECTORY_DEVELOCITY_ACCESS_KEY }}

      - name: Upload Build Info
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: Artifact BuildInfo
          path: target/scimple-*.buildinfo
